import { Noto_Serif as mainfont } from "next/font/google";
import { Inter as secondaryFont } from "next/font/google";
import "./../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/composite/Footer";
import PaddedContainer from "@/components/PaddedContainer";

const NotoSerif = mainfont({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const Inter = secondaryFont({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "YAZILAR -",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="tr"
      style={{
        background: "#fff",
      }}
    >
      {/* <Navbar transparent={true} /> */}
      <body className={NotoSerif.className}>
        <header className="fixed top-0 z-[20]">
          <Navbar transparent={false} />
        </header>
        <PaddedContainer className={"pt-[80px] max-sm:pt-[50px]"}>
          <div className="!min-h-[100vh]">
            <main>
              <article>{children}</article>
            </main>
          </div>
        </PaddedContainer>
        <Footer darkMode={true} />
      </body>
    </html>
  );
}
